### PR TITLE
Updated install docs, verified function on macOS

### PR DESCRIPTION
**Pull request by awillats**
Most of the changes are simple wording edits to introduction.md including adding sections and resources for python on mac.

Also have left in my paths to DF folders (using LazyMacPack) which maybe useful to be turned into examples as comments in the config.yaml

### CODE REVIEW

**Comment by pineapplemachine** [comment]
Thank you for contributing! I'll want to edit docs a little bit further, like in the config file, and ideally I'll take the time to check what's been changing in Dwarf Fortress over the years, see if anything needs updating, tidy up a couple of things, and then cut a new release. I might not find time for that for a week or two, depending on how things go, but this is good stuff and will definitely make it in soon. It's really great to see this tool still finding some use.

**Comment by pineapplemachine** [comment]
Oh my, some new things. Would you please either put the new scripts in a separate PR instead, or clean them up before they can accepted into a main release? For example `charcoalapple.testscript` is an empty no-op, there are lots of commented-out lines, and there's no readme file.

I'm happy to include these scripts in a release, but it's important to me that they are made polished and presentable first so that it's as easy as possible for other people to understand them and work with them. If you'd rather not I'll still accept the earlier changes, and regardless you are always free to distribute the files separately from PyDwarf so that people can add them by just dropping the directory in.

**Comment by pineapplemachine** [comment]
Ah, commenting in the correct place is hard. I meant for all these comments to be on the PR, but...

Please check the comments here, on this commit, for specific things I would request to be changed before the added scripts can be included in a release.

https://github.com/Charcoal-Apple/PyDwarf/commit/25cc7a107a244a617001a7a11f8ec822d994d8ad

**Comment by Charcoal-Apple** [comment]
I'll respond to some of the comments here, to keep them in a central place, but my intention was only to pull in the [Merge pull request #2 from awillats/mac_install ](https://github.com/Charcoal-Apple/PyDwarf/commit/4f2b5f64d87323f47ef2ae4982501e6e9d11e45c) commit, everything since then I probably should have put in a separate branch for myself

`GENERATOR` files:
the idea with these is to specify properties for things like workshops only using minimal changes, but allowing for something macro-like to fill in default properties. I'm currently just doing some simple find and replace using python.
If you know of any better solutions for doing this type of thing let me know! otherwise I'll be sure to better document what I'm doing when I polish these scrips 

thanks for the explanation of `permit_entities` that's good to know.

sidenote: Can I simply update my scripts to python3 syntax then call manager with `python3 manager.py` to get that to work? Simple changes like f-strings will mean it'll be easier to debug that way.

Concretely, I don't know if you can pull in that older commit without pulling the whole branch (?) so I'm going to separate out the new script in progress stuff to its own branch, revert this branch to only the documentation changes, then let you know here. Would that work?

**Comment by Charcoal-Apple** [comment]
okay, `Charcoal-Apple/PyDwarf/master` has now been (very clumsily) reverted to a state where it should be much easier to merge. It should only have 2 file changes
Screen Shot 2021-09-17 at 11 21 49 AM

even though, for whatever reason the pull request summary at the top of this page shows the old 16 files changes

please let me know if it looks like, from your side the work in progress charcoalapple scripts are still in there, or whether the reverting has worked

**Comment by pineapplemachine** [comment]
Looking at the PR changes I still see the added scripts files, for example, which would have to be cleaned up or reverted before I could accept the PR.

I can suggest making a new branch based off the earlier commit, and making a new PR using that branch, if it wasn't the intention to submit the scripts for inclusion in the release. I'm still happy to accept the original changes, once I find some time to get things settled on my end.

You'll also have to forgive some confusion on my part - @Charcoal-Apple how were you able to modify the PR branch submitted by @awillats? Is this the same person, two different accounts?

**Comment by pineapplemachine** [comment]
> sidenote: Can I simply update my scripts to python3 syntax then call manager with python3 manager.py to get that to work? Simple changes like f-strings will mean it'll be easier to debug that way.

If you plan to have the scripts included in a release? No, they will need to be both 2 and 3 compatible if they're going in the main release.

If you plan to have them for your own use, or release them separately? I _think_ that should be fine. It's been a while so my memory is fuzzy, or maybe things have changed with Python since then, but I think PyDwarf itself was both 2 and 3 compatible back when I was last working on it. Even though documentation states that Python 2 should be assumed for user scripts. (It seems like too much of a burden to expect all of everybody's scripts to be both 2 and 3 compatible. Core release should be as compatible as possible, though.) Before I cut a new release I intend to check that the actual repo and included scripts are fine for both 2 and 3 and fix any issues, and change the documentation to recommend Python 3 for user scripts instead, since Python 2 is no longer so widely used as it was when I first released this project.

> If you know of any better solutions for doing this type of thing let me know! otherwise I'll be sure to better document what I'm doing when I polish these scrips

Sorry to say I do not! I just assumed you were using an automated tool.

**Comment by Charcoal-Apple** [comment]
(yeah sorry for the confusion, @awillats is my "professional account" and I transferred this project over to @Charcoal-Apple, my "hobby account")

Okay. I'll simply make a clone of this branch then submit a new pull request (which should mean no new script directory)

**Comment by pineapplemachine** [comment]
Closing due to #11 being a revised version of this PR

**Pull request closed without merging**
